apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/clickhouse
