apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: http
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: tcp
  type: ClusterIP
